- name: "Ensure dependencies are installed"
  apt: >
    name={{ item }}
    state=present
    update_cache=yes
  with_items:
    - fontconfig
    - libfontconfig1
    - libfreetype6
    - libpng12-0
    - libxrender1
    - xfonts-base
    - xfonts-75dpi
  tags:
    - wkhtmltopdf
    - pkgs

- name: "Ensure libjpeg dependencies are installed"
  apt: >
    name={{ item }}
    state=present
  with_items:
    - libjpeg8
  when: ansible_distribution_release == "wheezy"
  tags:
    - wkhtmltopdf
    - pkgs

- name: "Ensure libjpeg dependencies are installed"
  apt: >
    name={{ item }}
    state=present
  with_items:
    - libjpeg62-turbo
  when: ansible_distribution_release == "jessie"
  tags:
    - wkhtmltopdf
    - pkgs

- name: "Download deb file for wkhtmltopdf"
  get_url: >
    url="http://download.gna.org/wkhtmltopdf/{{ wkhtmltopdf_version_main }}/{{ wkhtmltopdf_version_full }}/wkhtmltox-{{ wkhtmltopdf_version_full }}_linux-{{ ansible_distribution_release }}-{{ wkhtmltopdf_architecture }}.deb"
    dest="/tmp/wkhtmltox-{{ wkhtmltopdf_version_full }}_linux-{{ ansible_distribution_release }}-{{ wkhtmltopdf_architecture }}.deb"
  tags:
    - wkhtmltopdf
    - pkgs

- name: "Ensure wkhtmltopdf is installed"
  apt: >
    deb="/tmp/wkhtmltox-{{ wkhtmltopdf_version_full }}_linux-{{ ansible_distribution_release }}-{{ wkhtmltopdf_architecture }}.deb"
    state=present
  tags:
    - wkhtmltopdf
    - pkgs
